### ISSUE TITLE
"There is a problem with the API request."

### ISSUE THREAD

**Issue by chris93007-wq** [zeplin/connected-components-docs#18]
I ran zeplin connect
and logged in using the access token
I get - 
<img width="530" alt="Screen Shot 2020-04-15 at 4 12 48 PM" src="https://user-images.githubusercontent.com/63750494/79383892-f7763400-7f33-11ea-9217-3b1e4b103302.png">
This is the log file
[cli.log](https://github.com/zeplin/connected-components-docs/files/4483530/cli.log)

**Comment by yuqu** [comment]
Hey @chris93007-wq,

Logs show that you are receiving error from some kind of firewall or egress proxy. The request has not reach to our servers. The received error page in the logs looks like the following.

![image](https://user-images.githubusercontent.com/7137767/79385591-88b7cb80-7f71-11ea-91f8-eb863b80d374.png)

**Comment by yuqu** [comment]
I suggest you to checkout what is intercepting the request in your local network and why it is being blocked. We are making a PUT request to our API server to upload metadata about your connected components into our servers. Let me know you want to know any specifics about the request structure.

**Comment by chris93007-wq** [comment]
@yuqu We a proxy setup on all work laptops which we can't/shouldn't get around. Which I suppose is true of most enterprises. Is there some other alternative? We are able to use the use zeplin desktop app & web app. How is this different?

**Comment by yuqu** [comment]
Connected components request payloads has file names, generated code snippets etc. unlike Zeplin app. It is just my guess but it would trigger alerts on a security software since it would think you are uploading source code to somewhere unknown. I think our hostname should be whitelisted if that's the case. 

It is hard to tell what to do without knowing the reason why the request is flagged by your proxy.

**Comment by chris93007-wq** [comment]
I see, that's unfortunate for enterprises. Thanks anyway.
