### ISSUE TITLE
Use id instead of name to declare zeplin components

### ISSUE THREAD

**Issue by sayinserdar** [zeplin/connected-components-docs#34]
It would be really nice if an identifier array is used instead of `zeplinNames` array. 
Our team decided to change its naming convention and we have to change each components' name in our `components.json`. It would be smoother if it's based on id. :clinking_glasses:

**Comment by yuqu** [comment]
Hey, thanks for the suggestion. 

We have started to support component ids after @zeplin/cli@1.1.0 release. Documentation is on review now, will be published soon. In the meantime, you can access to the [branch](https://github.com/zeplin/connected-components-docs/tree/initialization) to see latest documentation.

Zeplin VSCode Extension is also going to be updated to support `zeplinIds` field very soon, you can track it on https://github.com/zeplin/vscode-extension/pull/112. There will be a command named `Migrate Zeplin Component names to ids in configuration` on the extension to convert all existing `zeplinNames` to their correspondent ids, I suggest you to use that command for a seamless migration.

**Comment by PoisonousJohn** [comment]
@yuqu hi. I see that you've added `zeplinIds` key to the configuration file, and it seems to be working via the CLI. Yet VSCode extension doesn't work with it, it does not suggest any action for this key

![image](https://user-images.githubusercontent.com/1488281/112004158-9935d600-8b32-11eb-8208-648b726d698a.png)

**Comment by yuqu** [comment]
@PoisonousJohn Hi, we just published a new release for VS Code Extension to address zeplinIds issues, could you update it and try again?

**Comment by yuqu** [comment]
@sayinserdar As I mentinoned on my comment above, VS Code Extension now supports using component IDs instead of components names on Connected Components configuration file. Check it out on [the revamped documentation](https://github.com/zeplin/connected-components-docs/blob/master/docs/gettingStarted/QUICK_START.md#using-vs-code-extension). 

You can use migrate command on the command palette to convert all existing zeplinNames to corresponding zeplinIds.
<img src="https://user-images.githubusercontent.com/7137767/112297979-90b2dc00-8ca7-11eb-9910-1ae4626be136.png" width="500" />
